# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c00c1424709da57dc33079cde85198d86518afd5c71cf034dcbeee87083c9a35c99d6ff3601e523715642c49480094092dca69db2c9a8f91e8c92708978df2e
  config_twitter_key: <%= ENV["CONFIG_TWITTER_KEY"] %>
  config_twitter_secret: <%= ENV["CONFIG_TWITTER_SECRET"] %>
  config_facebook_key: <%= ENV["CONFIG_FACEBOOK_KEY"] %>
  config_facebook_secret: <%= ENV["CONFIG_FACEBOOK_SECRET"] %>
  config_twitter_callback_url: http://127.0.0.1:3000/oauth/callback?provider=twitter
  config_facebook_callback_url: http://127.0.0.1:3000/oauth/callback?provider=facebook
  #config_aws_access_key_id: <%= ENV["S3_KEY"] %>
  #config_aws_secret_access_key: <%= ENV["S3_SECRET"] %>

test:
  secret_key_base: 5d84864f5fdcab359e48cf6138fa7bc5ece8311a37bb1a89a9fcedd69da10b1f2583262d2e4f562d8936feb2f796fc976b7f012e4709d787b4e95d7bd567af61
  config_twitter_key: <%= ENV["CONFIG_TWITTER_KEY"] %>
  config_twitter_secret: <%= ENV["CONFIG_TWITTER_SECRET"] %>
  config_facebook_key: <%= ENV["CONFIG_FACEBOOK_KEY"] %>
  config_facebook_secret: <%= ENV["CONFIG_FACEBOOK_SECRET"] %>
  #config_aws_access_key_id: <%= ENV["S3_KEY"] %>
  #config_aws_secret_access_key: <%= ENV["S3_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  config_twitter_key: <%= ENV["CONFIG_TWITTER_KEY"] %>
  config_twitter_secret: <%= ENV["CONFIG_TWITTER_SECRET"] %>
  config_facebook_key: <%= ENV["CONFIG_FACEBOOK_KEY"] %>
  config_facebook_secret: <%= ENV["CONFIG_FACEBOOK_SECRET"] %>
  #config_aws_access_key_id: <%= ENV["S3_KEY"] %>
  #config_aws_secret_access_key: <%= ENV["S3_SECRET"] %>
